import { motion } from 'framer-motion';
import type { PresentationTheme } from '../presentationThemes';

interface Props { theme: PresentationTheme; }

export function ConclusionSlide({ theme }: Props) {
  return (
    <div className="flex flex-col items-center justify-center h-full text-center px-24 relative overflow-hidden">
      {/* Decorative gradient orb */}
      <motion.div
        initial={{ opacity: 0, scale: 0 }}
        animate={{ opacity: 0.1, scale: 1 }}
        transition={{ duration: 1.5, ease: 'easeOut' }}
        className="absolute w-[800px] h-[800px] rounded-full pointer-events-none blur-3xl"
        style={{ background: theme.accent, top: '50%', left: '50%', transform: 'translate(-50%, -50%)' }}
      />

      <motion.h2 initial={{ opacity: 0, y: 30 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.1, duration: 0.8 }}
        className="text-7xl font-black mb-8" style={{ color: theme.text }}>
        Thank You
      </motion.h2>

      <motion.div initial={{ scaleX: 0 }} animate={{ scaleX: 1 }} transition={{ delay: 0.4, duration: 0.6 }}
        className="my-4 w-32 h-1 rounded" style={{ background: theme.accent }}
      />

      <motion.p initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.6 }}
        className="text-2xl mt-8 mb-4 font-medium" style={{ color: theme.textMuted }}>
        Questions & Discussion
      </motion.p>
      
      <motion.p initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: 0.8 }}
        className="text-lg opacity-60" style={{ color: theme.textMuted }}>
        Generated by Beam Analysis Studio
      </motion.p>
    </div>
  );
}
