/**
 * BeamLab B1.5 — CSI SAP2000 & ETABS Text Interop Provider (.s2k / .e2k)
 */

import { IInteropProvider, InteropFormat, InteropDirection, ImportOptions, ExportOptions } from '../InteropTypes';
import { EngineeringModel } from '../../model/EngineeringModel';
import { EngineeringNode, EngineeringMember } from '../../geometry/Geometry';
import { EngineeringSupport } from '../../boundary/Boundary';

export class Sap2000InteropProvider implements IInteropProvider<string> {
  readonly format: InteropFormat = 'sap2000';
  readonly name = 'CSI SAP2000 / ETABS Exchange Provider';
  readonly description = 'Bidirectional interchange of structural frames via CSI .s2k/.e2k text tables';
  readonly direction: InteropDirection = 'BiDirectional';
  readonly fileExtensions: readonly string[] = ['.s2k', '.e2k'];

  importModel(content: string, options?: ImportOptions): EngineeringModel {
    const model = new EngineeringModel(`model-sap-${Date.now()}`, {
      name: options?.structureName ?? 'Imported SAP2000 Model',
    });

    const lines = content.split(/\r?\n/);
    let table = '';

    const mat = model.addMaterial('mat-a992', 'A992 Steel', 200e9, 77e9, 0.3, 7850, 'Steel');
    const sec = model.addSection('sec-w12x26', 'W12x26', 4.94e-3, 7.2e-6, 8.49e-5, 1.25e-7);

    for (let rawLine of lines) {
      const line = rawLine.trim();
      if (!line || line.startsWith(';')) continue;

      if (line.startsWith('TABLE:')) {
        const match = line.match(/TABLE:\s*"([^"]+)"/);
        table = match && match[1] ? match[1].toUpperCase() : '';
        continue;
      }

      if (table.includes('JOINT COORDINATES')) {
        // e.g. Joint=1  CoordSys=GLOBAL  XorR=0  Y=0  Z=0
        const jMatch = line.match(/Joint=([^\s]+)/i);
        const xMatch = line.match(/XorR=([-\d.eE]+)/i);
        const yMatch = line.match(/Y=([-\d.eE]+)/i);
        const zMatch = line.match(/Z=([-\d.eE]+)/i);

        if (jMatch && jMatch[1] && xMatch && yMatch) {
          const jId = `node-${jMatch[1]}`;
          const name = `N${jMatch[1]}`;
          const x = parseFloat(xMatch[1] ?? '0');
          const y = parseFloat(yMatch[1] ?? '0');
          const z = zMatch && zMatch[1] ? parseFloat(zMatch[1]) : 0;
          model.addNode(jId, name, x, y, z, 'structure-main');
        }
      } else if (table.includes('CONNECTIVITY - FRAME') || table.includes('LINE CONNECTIVITY')) {
        // e.g. Frame=1  JointI=1  JointJ=2
        const fMatch = line.match(/Frame=([^\s]+)/i);
        const iMatch = line.match(/JointI=([^\s]+)/i);
        const jMatch = line.match(/JointJ=([^\s]+)/i);

        if (fMatch && fMatch[1] && iMatch && jMatch && iMatch[1] && jMatch[1]) {
          const fId = `mem-${fMatch[1]}`;
          const name = `F${fMatch[1]}`;
          const startId = `node-${iMatch[1]}`;
          const endId = `node-${jMatch[1]}`;
          model.addMember(fId, name, startId, endId, mat.identity.id, sec.identity.id, 'structure-main');
        }
      } else if (table.includes('JOINT RESTRAINT ASSIGNMENTS')) {
        // e.g. Joint=1  U1=Yes  U2=Yes  U3=Yes  R1=No  R2=No  R3=No
        const jMatch = line.match(/Joint=([^\s]+)/i);
        if (jMatch && jMatch[1]) {
          const nodeId = `node-${jMatch[1]}`;
          const u1 = /U1=Yes/i.test(line);
          const u2 = /U2=Yes/i.test(line);
          const u3 = /U3=Yes/i.test(line);
          const r1 = /R1=Yes/i.test(line);
          const r2 = /R2=Yes/i.test(line);
          const r3 = /R3=Yes/i.test(line);
          const sup = model.addSupport(`sup-${jMatch[1]}`, `Support-${nodeId}`, nodeId, 'structure-main');
          sup.restraints = {
            dx: u1,
            dy: u2,
            dz: u3,
            rx: r1,
            ry: r2,
            rz: r3,
          };
        }
      }
    }

    return model;
  }

  exportModel(model: EngineeringModel, _options?: ExportOptions): string {
    const lines: string[] = [
      '; CSI SAP2000 / ETABS Text Data File (.s2k)',
      '; Generated by BeamLab B1.5 Interoperability Engine',
      `; Date: ${new Date().toISOString()}`,
      '',
      'TABLE:  "PROGRAM INFORMATION"',
      '   ProgramName=SAP2000   Version=24.0.0   ProgLevel=Ultimate',
      '',
      'TABLE:  "JOINT COORDINATES"',
    ];

    let jIndex = 1;
    const nodeToIdx = new Map<string, number>();
    for (const node of model.objects.getByType<EngineeringNode>('Node')) {
      const idx = jIndex++;
      nodeToIdx.set(node.identity.id, idx);
      const x = node.x.toFixed(4);
      const y = node.y.toFixed(4);
      const z = node.z.toFixed(4);
      lines.push(`   Joint=${idx}   CoordSys=GLOBAL   CoordType=Cartesian   XorR=${x}   Y=${y}   Z=${z}   SpecialJt=No`);
    }

    lines.push('', 'TABLE:  "CONNECTIVITY - FRAME"');
    let fIndex = 1;
    for (const mem of model.objects.getByType<EngineeringMember>('Member')) {
      const idx = fIndex++;
      const s = nodeToIdx.get(mem.startNodeId) ?? 1;
      const e = nodeToIdx.get(mem.endNodeId) ?? 2;
      lines.push(`   Frame=${idx}   JointI=${s}   JointJ=${e}   IsCurved=No`);
    }

    lines.push('', 'TABLE:  "JOINT RESTRAINT ASSIGNMENTS"');
    for (const sup of model.objects.getByType<EngineeringSupport>('Support')) {
      const nIdx = nodeToIdx.get(sup.nodeId);
      if (nIdx) {
        const r = sup.restraints ?? { dx: true, dy: true, dz: true, rx: false, ry: false, rz: false };
        lines.push(`   Joint=${nIdx}   U1=${r.dx ? 'Yes' : 'No'}   U2=${r.dy ? 'Yes' : 'No'}   U3=${r.dz ? 'Yes' : 'No'}   R1=${r.rx ? 'Yes' : 'No'}   R2=${r.ry ? 'Yes' : 'No'}   R3=${r.rz ? 'Yes' : 'No'}`);
      }
    }

    lines.push('', 'END TABLE DATA');
    return lines.join('\n');
  }
}
